# Configuration based on https://github.com/zalando/problem-spring-web/tree/master/problem-spring-web#configuration
spring:
  http:
    encoding:
      force: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  security:    user:      password: secret
